export const ALL_INGREDIENTS: string[] = [
  "Abalone",
  "Abiyuch",
  "Acerola",
  "Achilleas",
  "Acorn",
  "Adobo",
  "Adzuki bean",
  "Agar",
  "Agave",
  "Akutaq",
  "Alaska blackfish",
  "Alaska pollock",
  "Alaska wild rhubarb",
  "Albacore tuna",
  "Alfalfa",
  "Allium",
  "Allspice",
  "Almond",
  "Alpine sweetvetch",
  "Alpinia",
  "Amaranth",
  "American butterfish",
  "American pokeweed",
  "American shad",
  "Anatidae",
  "Anchovy",
  "Angelica",
  "Anguilliformes",
  "Anise",
  "Anise Brandy",
  "Anise Hyssop",
  "Annual wild rice",
  "Apple",
  "Apple Brandy",
  "Apple Cider Vinegar",
  "Apple Sauce",
  "Apricot",
  "Arabica coffee",
  "Arar",
  "Arepa",
  "Armagnac Brandy",
  "Arrack",
  "Arrowhead",
  "Arrowroot",
  "Artemisia",
  "Artichoke",
  "Asafoetida",
  "Ascidians",
  "Ashgourd",
  "Asparagus",
  "Atlantic croaker",
  "Atlantic halibut",
  "Atlantic herring",
  "Atlantic mackerel",
  "Atlantic menhaden",
  "Atlantic pollock",
  "Atlantic salmon",
  "Atlantic wolffish",
  "Avocado",
  "Babaco",
  "Babassu palm",
  "Bagel",
  "Baked potato",
  "Bakery Products",
  "Bamboo shoots",
  "Banana",
  "Bantu Beer",
  "Barley",
  "Bartlett Pear",
  "Basil",
  "Basmati Rice",
  "Bayberry",
  "Beans",
  "Bearded seal",
  "Beaver",
  "Beech nut",
  "Beef",
  "Beef Processed",
  "Beefalo",
  "Beer",
  "Beetroot",
  "Beli",
  "Beluga whale",
  "Bergamot",
  "Berry",
  "Berry wine",
  "Beverage alcolohic other",
  "Bilberry",
  "Bilberry Wine",
  "Biscuit",
  "Bison",
  "Bitter Cherry",
  "Bitter Orange",
  "Bittergourd",
  "Bivalvia",
  "Black Currant",
  "Black Tea",
  "Black bear",
  "Black crowberry",
  "Black huckleberry",
  "Black mulberry",
  "Black raspberry",
  "Black salsify",
  "Black-eyed pea",
  "Blackberry",
  "Blackberry Brandy",
  "Blue Cheese",
  "Blue whiting",
  "Blueberry",
  "Bluefish",
  "Bonito",
  "Borage",
  "Botrytized Wine",
  "Bottlegourd",
  "Bourbon Whisky",
  "Bowhead whale",
  "Boysenberry",
  "Brandy",
  "Brazil Nut",
  "Bread",
  "Breadfruit",
  "Breadnut tree seed",
  "Breakfast cereal",
  "Breakfast sandwich",
  "Broad whitefish",
  "Broccoli",
  "Brown bear",
  "Brussels Sprout",
  "Buchu",
  "Buckwheat",
  "Buffalo",
  "Buffalo currant",
  "Bulgur",
  "Burbot",
  "Burdock",
  "Burrito",
  "Butter",
  "Buttermilk",
  "Butternut",
  "Butternut squash",
  "Byrsonima crassifolia",
  "Cabbage",
  "Cajeput",
  "Cake",
  "Calamus",
  "Camembert Cheese",
  "Camphor",
  "Canada blueberry",
  "Canadian Whisky",
  "Candy bar",
  "Canola Oil",
  "Capers",
  "Capsicum",
  "Caraway",
  "Cardamom",
  "Cardoon",
  "Caribou",
  "Carob",
  "Carom Seed",
  "Carp bream",
  "Carrot",
  "Cascarilla",
  "Casein",
  "Cashew Apple",
  "Cashew nut",
  "Cassava",
  "Cassia",
  "Catfish",
  "Catjang pea",
  "Cauliflower",
  "Caviar",
  "Cedar",
  "Celery",
  "Ceriman",
  "Cetacea",
  "Chamomile",
  "Champaca",
  "Champagne",
  "Channel catfish",
  "Chanterelle",
  "Chard",
  "Charr",
  "Chayote",
  "Cheddar Cheese",
  "Cheese",
  "Cherimoya",
  "Cherry",
  "Cherry Brandy",
  "Cherry Pepper",
  "Cherry tomato",
  "Chervil",
  "Chestnut",
  "Chewing gum",
  "Chia",
  "Chicken",
  "Chickpea",
  "Chicory",
  "Chili",
  "Chimichanga",
  "Chinese Quince",
  "Chinese bayberry",
  "Chinese chestnut",
  "Chinook salmon",
  "Chive",
  "Chocolate",
  "Chocolate mousse",
  "Chocolate spread",
  "Chum salmon",
  "Cichlidae",
  "Cider",
  "Cinnamon",
  "Cisco",
  "Citronella",
  "Citrus Fruits",
  "Citrus Peel Oil",
  "Clam",
  "Clary Sage",
  "Climbing bean",
  "Cloud ear fungus",
  "Cloudberry",
  "Clove",
  "Clupeinae",
  "Cluster Bean",
  "Cocktail",
  "Cocoa",
  "Cocoa butter",
  "Cocoa powder",
  "Coconut",
  "Codfish",
  "Coffee",
  "Coffee mocha",
  "Cognac Brandy",
  "Coho salmon",
  "Cold cut",
  "Colocasia",
  "Colorado pinyon",
  "Columbidae",
  "Common Tuna",
  "Common carp",
  "Common dab",
  "Common ling",
  "Common octopus",
  "Common persimmon",
  "Common salsify",
  "Common verbena",
  "Comte Cheese",
  "Conch",
  "Condensed milk",
  "Cooking oil",
  "Coriander",
  "Corn",
  "Corn Oil",
  "Corn chip",
  "Corn grits",
  "Corn salad",
  "Cornbread",
  "Cornmint",
  "Cottage Cheese",
  "Cottonseed",
  "Couscous",
  "Crab",
  "Cranberry",
  "Crayfish",
  "Cream",
  "Cream Cheese",
  "Creosote",
  "Crispbread",
  "Cucumber",
  "Cucurbita",
  "Cumin",
  "Cupua\u008du",
  "Currant",
  "Curry Leaf",
  "Cusk",
  "Cuttlefish",
  "Dairy Products",
  "Dandelion",
  "Dates",
  "Deer",
  "Deerberry",
  "Devilfish",
  "Dill",
  "Dock",
  "Dolphin fish",
  "Domiati Cheese",
  "Drag\u00e9e",
  "Drumstick Leaf",
  "Dulce de leche",
  "Dumpling",
  "Durian",
  "Egg roll",
  "Eggplant",
  "Elderberry",
  "Elk",
  "Elliott's blueberry",
  "Emmental Cheese",
  "Empanada",
  "Emu",
  "Enchilada",
  "Endive",
  "Energy drink",
  "Enokitake",
  "Epazote",
  "Eucalyptus",
  "European anchovy",
  "European chestnut",
  "European rabbit",
  "Evaporated milk",
  "Evening primrose",
  "Falafel",
  "Fatty Fish",
  "Feijoa",
  "Fennel",
  "Fenugreek",
  "Fermented Tea",
  "Feta Cheese",
  "Fig",
  "Filbert",
  "Finnish Whisky",
  "Fir",
  "Fireweed",
  "Fish",
  "Fish Oil",
  "Fish burger",
  "Flatfish",
  "Flaxseed",
  "Florida pompano",
  "Flour",
  "Focaccia",
  "Frankfurter Sausage",
  "French plantain",
  "French toast",
  "Freshwater drum",
  "Freshwater eel",
  "Fried Potato",
  "Fruit gum",
  "Fruit juice",
  "Fruit preserve",
  "Fruit salad",
  "Frybread",
  "Fudge",
  "Gadiformes",
  "Garcinia Indica",
  "Garden cress",
  "Garfish",
  "Garland chrysanthemum",
  "Garlic",
  "Gefilte fish",
  "Gelatin",
  "Gelatin dessert",
  "Geranium",
  "Ghee",
  "Giant butterbur",
  "Gin",
  "Ginger",
  "Ginkgo nuts",
  "Ginseng",
  "Goat Cheese",
  "Goat Milk",
  "Gooseberry",
  "Gram bean",
  "Grape",
  "Grapefruit",
  "Grapefruit Peel Oil",
  "Grass",
  "Grass pea",
  "Great horned owl",
  "Greater sturgeon",
  "Green Beans",
  "Green Tea",
  "Green turtle",
  "Green zucchini",
  "Greenland halibut",
  "Greenthread tea",
  "Greylag goose",
  "Groundcherry",
  "Grouper",
  "Gruyere Cheese",
  "Guava",
  "Guinea hen",
  "Haddock",
  "Ham",
  "Hamburger",
  "Hard wheat",
  "Hazelnut",
  "Heart of palm",
  "Hedge mustard",
  "Hibiscus tea",
  "Hippoglossus",
  "Hogplum",
  "Honey",
  "Hops",
  "Hops Oil",
  "Horchata",
  "Horned melon",
  "Horse",
  "Horseradish",
  "Hot chocolate",
  "Hot dog",
  "Hummus",
  "Hushpuppy",
  "Hyacinth",
  "Hyacinth bean",
  "Hyssop Oil",
  "Ice cream",
  "Ice cream cone",
  "Icing",
  "Irish moss",
  "Jackfruit",
  "Jalapeno",
  "Japanese Whisky",
  "Japanese chestnut",
  "Japanese persimmon",
  "Japanese pumpkin",
  "Jasmine",
  "Jellyfish",
  "Jerusalem artichoke",
  "Jew's ear",
  "Jicama",
  "Jostaberry",
  "Jujube",
  "Junket",
  "Jute",
  "Kai lan",
  "Kale",
  "Kefir",
  "Kelp",
  "Kenaf",
  "Ketchup",
  "Kewda",
  "Kidney Beans",
  "King mackerel",
  "Kiwifruit",
  "Kohlrabi",
  "Komatsuna",
  "Kombu",
  "Krill",
  "Kumquat",
  "Lake trout",
  "Lamb",
  "Lambsquarters",
  "Lasagna",
  "Laurel",
  "Lavendar",
  "Lean Fish",
  "Leather chiton",
  "Leavening agent",
  "Leek",
  "Lemon",
  "Lemon Balm",
  "Lemon Grass",
  "Lemon Peel Oil",
  "Lemon sole",
  "Lemon verbena",
  "Lentils",
  "Lettuce",
  "Lima Beans",
  "Limburger Cheese",
  "Lime",
  "Lime Peel Oil",
  "Linden",
  "Lingcod",
  "Lingonberry",
  "Liqourice",
  "Litchi",
  "Lobster",
  "Loganberry",
  "Longan",
  "Loquat",
  "Lotus",
  "Lovage",
  "Lumpsucker",
  "Lupine",
  "Macadamia Nut",
  "Macaroni",
  "Macaroni and cheese",
  "Mace",
  "Madeira wine",
  "Maitake",
  "Malabar plum",
  "Malabar spinach",
  "Malay Apple",
  "Mallard duck",
  "Malt",
  "Malt Whisky",
  "Mammee apple",
  "Mandarin Orange",
  "Mandarin Orange Peel Oil",
  "Mango",
  "Margarine",
  "Margarine like spread",
  "Marjoram",
  "Marshmallow",
  "Marzipan",
  "Mastic Gum",
  "Mate",
  "Meat",
  "Meat bouillon",
  "Meatball",
  "Meatloaf",
  "Medlar",
  "Melon",
  "Mentha Oil",
  "Meringue",
  "Mexican groundcherry",
  "Mexican oregano",
  "Milk",
  "Milk Fat",
  "Milk Human",
  "Milk Powder",
  "Milkfish",
  "Milkshake",
  "Millet",
  "Mint",
  "Miso",
  "Mixed nuts",
  "Molasses",
  "Mollusc",
  "Monkfish",
  "Moose",
  "Morchella",
  "Moth bean",
  "Mountain Papaya",
  "Mountain hare",
  "Mountain yam",
  "Mozzarella Cheese",
  "Mulberry",
  "Mule deer",
  "Multigrain bread",
  "Mung bean",
  "Munster Cheese",
  "Muscadine grape",
  "Mushroom",
  "Musk Melon",
  "Muskmallow",
  "Muskrat",
  "Mustard",
  "Mustard Oil",
  "Mutton",
  "Myrrh",
  "Myrtle",
  "Nachos",
  "Nance",
  "Nanking cherry",
  "Naranjilla",
  "Narrowleaf cattail",
  "Natal plum",
  "Natto",
  "Neroli Oil",
  "New Zealand spinach",
  "Nigella Seed",
  "Nopal",
  "North Pacific giant octopus",
  "Northern bluefin tuna",
  "Northern pike",
  "Norway haddock",
  "Norway pout",
  "Nougat",
  "Nutmeg",
  "Nutritional drink",
  "Nuts",
  "Nuttall cockle",
  "Oat bread",
  "Oats",
  "Ocean pout",
  "Ohelo berry",
  "Oil palm",
  "Oil-seed Camellia",
  "Okra",
  "Olive",
  "Onion",
  "Opossum",
  "Orange",
  "Orange Oil",
  "Orange roughy",
  "Oregano",
  "Oregon yampah",
  "Oriental wheat",
  "Orris",
  "Ostrich",
  "Ostrich fern",
  "Other Cheeses",
  "Other bread product",
  "Other dish",
  "Other fermented milk",
  "Other fish product",
  "Other frozen dessert",
  "Other meat product",
  "Other pasta dish",
  "Other sandwich",
  "Other snack food",
  "Oyster",
  "Oyster mushroom",
  "Pacific herring",
  "Pacific jack mackerel",
  "Pacific ocean perch",
  "Pacific rockfish",
  "Pacific sardine",
  "Painted comber",
  "Pak choy",
  "Pan dulce",
  "Pancake",
  "Paneer",
  "Papaya",
  "Papaya Brandy",
  "Parmesan Cheese",
  "Parsley",
  "Parsnip",
  "Passionfruit",
  "Pasta",
  "Pastry",
  "Pate",
  "Pawpaw",
  "Peach",
  "Peanut",
  "Peanut Butter",
  "Peanut Oil",
  "Pear",
  "Pear Brandy",
  "Peas",
  "Pecans",
  "Pectin",
  "Pepino",
  "Pepper",
  "Pepper C. baccatum",
  "Pepper C. chinense",
  "Peppermint",
  "Perciformes",
  "Percoidei",
  "Persimmon",
  "Pheasant",
  "Phyllo dough",
  "Pie",
  "Pie crust",
  "Pigeon Pea",
  "Pikeperch",
  "Piki bread",
  "Pili nut",
  "Pine",
  "Pineapple",
  "Pineappple sage",
  "Pink salmon",
  "Pistachio",
  "Pita bread",
  "Pitanga",
  "Pizza",
  "Pleuronectidae",
  "Plum",
  "Plum Brandy",
  "Plum Wine",
  "Plumcot",
  "Polar bear",
  "Pollock",
  "Pomegranate",
  "Popcorn",
  "Poppy Seed",
  "Pork",
  "Port Wine",
  "Pot pie",
  "Potato",
  "Potato bread",
  "Potato chip",
  "Potato gratin",
  "Potato puffs",
  "Prairie turnip",
  "Prawn",
  "Prickly Pear",
  "Provolone Cheese",
  "Pudding",
  "Pummelo",
  "Pumpkin",
  "Pumpkinseed sunfish",
  "Pupusa",
  "Purple laver",
  "Purple mangosteen",
  "Purslane",
  "Quail",
  "Quesadilla",
  "Quince",
  "Quinoa",
  "Rabbit",
  "Raccoon",
  "Radish",
  "Rainbow smelt",
  "Rainbow trout",
  "Raisin",
  "Raisin bread",
  "Rambutan",
  "Rapini",
  "Raspberry",
  "Raspberry Brandy",
  "Ravioli",
  "Red Currant",
  "Red Sage",
  "Red Wine",
  "Red algae",
  "Red king crab",
  "Red raspberry",
  "Red rice",
  "Relish",
  "Remoulade",
  "Rhubarb",
  "Rice",
  "Rice bread",
  "Rice cake",
  "Ricotta Cheese",
  "Ringed seal",
  "Rock ptarmigan",
  "Rocket salad",
  "Roe",
  "Roibos Tea",
  "Romano Cheese",
  "Roquefort Cheese",
  "Rose",
  "Rose Wine",
  "Rose hip",
  "Roseapple",
  "Roselle",
  "Rosemary",
  "Rowal",
  "Rowanberry",
  "Rum",
  "Russian Cheese",
  "Rutabaga",
  "Rye",
  "Rye Bread",
  "Sablefish",
  "Safflower",
  "Saffron",
  "Sage",
  "Sago palm",
  "Sake",
  "Salad",
  "Salad dressing",
  "Salmon",
  "Salmonberry",
  "Salmonidae",
  "Salt",
  "Sandalwood",
  "Sapodilla",
  "Saskatoon berry",
  "Sassafras",
  "Satsuma Orange",
  "Sauce",
  "Sausage",
  "Scallop",
  "Scarlet bean",
  "Scombridae",
  "Scotch Spearmint",
  "Scotch Whisky",
  "Scrapple",
  "Scup",
  "Sea Buckthorns",
  "Sea cucumber",
  "Sea trout",
  "Semolina",
  "Sesame",
  "Sesbania flower",
  "Shallot",
  "Shark",
  "Shea tree",
  "Sheefish",
  "Sheep Cheese",
  "Sheep Milk",
  "Sheepshead",
  "Shellfish",
  "Sherry",
  "Shiitake",
  "Shortening",
  "Shrimp",
  "Silver linden",
  "Skimmed Milk",
  "Skunk currant",
  "Small leaf linden",
  "Smelt",
  "Smoked Fish",
  "Snack bar",
  "Snail",
  "Snapper",
  "Sockeye salmon",
  "Soft drink",
  "Sorghum",
  "Sorrel",
  "Soup",
  "Sour Cherry",
  "Sourdock",
  "Sourdough",
  "Soursop",
  "Soy cream",
  "Soy milk",
  "Soy yogurt",
  "Soybean",
  "Soybean Oil",
  "Soybean Sauce",
  "Spanish Sage",
  "Spanish mackerel",
  "Sparkleberry",
  "Sparkling Wine",
  "Spearmint",
  "Spelt",
  "Spinach",
  "Spineless Monkey Orange",
  "Spiny dogfish",
  "Spiny lobster",
  "Spirit",
  "Spirulina",
  "Spot croaker",
  "Spotted seal",
  "Spread",
  "Squab",
  "Squashberry",
  "Squid",
  "Squirrel",
  "Star Anise",
  "Starfruit",
  "Steller sea lion",
  "Stew",
  "Storax",
  "Strawberry",
  "Strawberry Jam",
  "Strawberry Wine",
  "Striped bass",
  "Striped mullet",
  "Stuffing",
  "Sturgeon",
  "Succotash",
  "Sugar",
  "Sugar substitute",
  "Sukiyaki",
  "Summer savory",
  "Sunflower",
  "Swamp cabbage",
  "Sweet Grass",
  "Sweet Potato",
  "Sweet custard",
  "Sweetcorn",
  "Swiss Cheese",
  "Swordfish",
  "Syrup",
  "Taco",
  "Tamale",
  "Tamarind",
  "Tangerine",
  "Tapioca pearl",
  "Taro",
  "Tarragon",
  "Tartary buckwheat",
  "Tea",
  "Tea leaf willow",
  "Teff",
  "Thistle",
  "Thyme",
  "Tilefish",
  "Tilsit Cheese",
  "Tinda",
  "Tobacco",
  "Toffee",
  "Tofu",
  "Tomato",
  "Topping",
  "Tortilla",
  "Tortilla chip",
  "Tostada",
  "Towel gourd",
  "Trail mix",
  "Trassi",
  "Tree fern",
  "Triticale",
  "True frog",
  "True seal",
  "True sole",
  "Truffle",
  "Turbot",
  "Turkey",
  "Turkey Berry",
  "Turmeric",
  "Turnip",
  "Ucuhuba",
  "Valerian",
  "Vanilla",
  "Vegetable juice",
  "Vegetarian food",
  "Vermouth",
  "Vinegar",
  "Vodka",
  "Waffle",
  "Wakame",
  "Walleye",
  "Walnut",
  "Walrus",
  "Wasabi",
  "Water",
  "Water Chestnut",
  "Watercress",
  "Wattle",
  "Weinbrand Brandy",
  "Welsh onion",
  "Wheat",
  "Wheaten Bread",
  "Whelk",
  "Whey",
  "Whisky",
  "White Bread",
  "White Currant",
  "White Pepper",
  "White Wine",
  "White lupine",
  "White sucker",
  "Whitefish",
  "Whiting",
  "Wholewheat Bread",
  "Wild Cherry",
  "Wild boar",
  "Wild rice",
  "Wine",
  "Winged bean",
  "Winter savory",
  "Winter squash",
  "Wonton wrapper",
  "Woodapple",
  "Wort",
  "Yam",
  "Yardlong bean",
  "Yarrow",
  "Yautia",
  "Yellow Passionfruit",
  "Yellow pond lily",
  "Yellow zucchini",
  "Yellowfin tuna",
  "Yellowtail amberjack",
  "Ylang-Ylang",
  "Ymer",
  "Yogurt",
  "Zwieback",
  "redskin onion"
]
